### ISSUE TITLE
Doesn't Work on Android

### ISSUE THREAD

**Issue by UtsavPreet** [evrone/flutter_audio#4]
I can't get it to run on Android, it constantly shows No Permissions, which is a bit annoying. Can you please look into this ?

**Comment by john2088** [comment]
can not play the audio on android 
i get the errors

**Comment by dimmetrius** [comment]
Hello Please add audio permission to manifest
```xml
<uses-permission android:name="android.permission.RECORD_AUDIO" />
```

**Comment by UtsavPreet** [comment]
Hey
I had given that a try but still it did throw an error. 
I'll try once again.
Thanks
